import { defineStore } from 'pinia'

export const useImageStore = defineStore('image', {
  state: () => ({
    images: [
      {
        name: 'fabianpoels_landscape_dolomites_storm',
        slug: 'landscape-dolomites-storm',
        description: 'Storm in the dolomites',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_climbing_finale_lubna',
        slug: 'climbing-finale-lubna',
        description: "Lubna, Grotta dell'Edera, Finale (ITALY)",
        width: 360,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_langkofel',
        slug: 'landscape-dolomites-langkofel',
        description: 'Langkofel, Dolomites (ITALY)',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_airplane',
        slug: 'landscape-airplane-sky',
        description: 'Airplane',
        width: 360,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_val_badia',
        slug: 'landscape-dolomites-heiligkreuzkofel',
        description: 'Heiligkreuzkofel, Val Badia, Dolomites (ITALY)',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_climbing_cikola',
        slug: 'climbing-croatia-cikola',
        description: "Nina Landekar on 'Grenguar', Čikola (CROATIA)",
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_krka',
        slug: 'landscape-croatia-krka',
        description: 'Krka national park (CROATIA)',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_frost',
        slug: 'landscape-frost',
        description: 'Frost',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_lagodigarda',
        slug: 'landscape-lago-di-garda-italy',
        description: 'Sunset on Lago di Garda (ITALY)',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_autumntrees',
        slug: 'landscape-autumn-trees',
        description: 'Autumn trees',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_portrait_italianguy',
        slug: 'portrait-italian-guy',
        description: 'Italian guy',
        width: 809,
        height: 540,
      },
      {
        name: 'fabianpoels_climbing_finale_roccadicorno',
        slug: 'climbing-finale-rocca-di-corno',
        description: 'Rombo di Vento, Rocca di Corno, Finale (ITALY)',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_lightning',
        slug: 'landscape-lightning',
        description: 'Lightning',
        width: 808,
        height: 540,
      },
      {
        name: 'fabianpoels_climbing_lumignano_boomerang',
        slug: 'climbing-lumignano-boomerang-italy-cody-roth',
        description: 'Cody Roth on Boomerang, Lumignano (ITALY)',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_portrait_lithuanian_girl',
        slug: 'portrait-lithuanian-girl',
        description: 'Lithuanian girl',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_landscape_rain',
        slug: 'landscape-rain',
        description: 'Rain',
        width: 808,
        height: 540,
      },
      {
        name: 'fabianpoels_climbing_menhir',
        slug: 'climbing-dolomites-menhir-italy-thomas-prenn',
        description: 'Thomas Prenn on Menhir, Passo Gardena, Dolomites (ITALY)',
        width: 361,
        height: 540,
      },
      {
        name: 'fabianpoels_portrait_italianbride',
        slug: 'portrait-italian-bride',
        description: 'Italian bride',
        width: 361,
        height: 540,
      },
    ],
  }),
  getters: {},
  actions: {},
})
